components:
  schemas:
    ErrorResponse:
      description: JSON response containing details of the error message
      properties:
        message:
          type: string
        messageArgs:
          description: List of arguments to be substituted in the error message.
          items:
            type: string
          type: array
        messageID:
          description: Contains the message id for the reported HTTP error code.
          type: string
        recommendedActions:
          description: List of recommended actions for the error occured.
          items:
            type: string
          type: array
      title: ErrorResponse
      type: object
    Upload_Response:
      properties:
        content-Length:
          description: Number of bytes/characters in the file.
          type: string
        uploadStartTime:
          description: Time of upload
          type: string
        version:
          description: "Version of the uploaded file if it\u2019s a software package."
          type: string
      title: Upload Response
      type: object
info:
  description: "ROHIT TESTING API SPECIFICATION DESCRIPTION"
  title: ROHIT Upload REST API specifications
  version: 1.0.0
openapi: 3.0.1
paths:
  /upload:
    post:
      description: ''
      parameters:
      - description: "Version of the uploaded file if it\u2019s a software package."
        in: query
        name: version
        schema:
          type: string
      - description: Number of bytes/characters in the file.
        in: query
        name: content-Length
        schema:
          type: string
      - description: Time of upload
        in: query
        name: uploadStartTime
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Upload_Response'
          description: Success
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unsupported file format
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Invalid authorization token
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: 'User does not possess authorization to perform this request.  '
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unexpected internal error
      summary: Upload
      tags:
      - Upload
servers:
- description: Base URL
  url: https://{server}:{port}/rest/v1/
  variables:
    port:
      default: '8443'
    server:
      default: 0.0.0.0
      description: ROHIT server IP
tags:
- name: Upload
